server:
  error:
    include-exception: false
    include-stacktrace: never

  servlet:
    context-path: /eos_view
data:
  tile:
    root: 'file:/Z:/DATA/MDA/tile'

basemap:
  key: 'CF1E6214-91ED-342A-BDB4-B54554CACF78'